config/routes.rb
Rails.application.routes.draw do
  root 'cads#index'
  resources :cads
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cad.rb
class Cad < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cads_controller.rb
class CadsController < ApplicationController
  before_action :set_cad, only: %i[ show edit update destroy ]

  # GET /cads or /cads.json
  def index
    @cads = Cad.all
  end

  # GET /cads/1 or /cads/1.json
  def show
  end

  # GET /cads/new
  def new
    @cad = Cad.new
  end

  # GET /cads/1/edit
  def edit
  end

  # POST /cads or /cads.json
  def create
    @cad = Cad.new(cad_params)

    respond_to do |format|
      if @cad.save
        format.html { redirect_to @cad, notice: "Cad was successfully created." }
        format.json { render :show, status: :created, location: @cad }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cads/1 or /cads/1.json
  def update
    respond_to do |format|
      if @cad.update(cad_params)
        format.html { redirect_to @cad, notice: "Cad was successfully updated." }
        format.json { render :show, status: :ok, location: @cad }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cads/1 or /cads/1.json
  def destroy
    @cad.destroy
    respond_to do |format|
      format.html { redirect_to cads_url, notice: "Cad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cad
      @cad = Cad.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cad_params
      params.require(:cad).permit(:nome, :cnpjcpf, :ie, :celular, :telefone, :nomecont, :dtnasc, :celular2, :telefone2, :nomecont2, :email, :cep, :rua, :numcasa, :cidade, :bairro, :estado, :pais)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cads_helper.rb
module CadsHelper
end

app/views/cads/_form.html.erb
<%= form_with(model: cad) do |form| %>
  <% if cad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cad.errors.count, "error") %> prohibited this cad from being saved:</h2>

      <ul>
        <% cad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    
  <form>
  <div class="field"></div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%=form.text_field :nome, placeholder:"Nome", class:"form-control"%>
      </div>
      <div class="field"></div>
      <div class="form-group col-md-6">
        <%= form.text_field :cnpjcpf, placeholder:"CNPJ/CPF", class:"form-control" %>
      </div>  
    </div> 
  </form> 

  <div class="field">
    <div class="form-group col-6">
      <div class="field"></div>
      <%= form.text_field :ie, placeholder:"Inscrição Estadual",class:"form-control" %>
    </div> 
  </div>

  <div class="field">
    <div class="form-group col-6">
      <div class="field"></div>
      <%= form.text_field :celular, placeholder:"Celular", class:"form-control" %>
    </div>
  </div>

  <div class="field">
    <div class="form-group col-6">
      <div class="field"></div>
      <%= form.text_field :telefone, placeholder:"Telefone:", class:"form-control" %>
    </div>
  </div>

  <div class="field">
    <div class="form-group col-6">
      <div class="field"></div>
      <%= form.text_field :nomecont, placeholder: "Contato", class:"form-control"%>
    </div>  
  </div>

  <div class="field">
     <div class="form-group col-6">
      <div class="field"></div> 
      <%= form.date_select :dtnasc, :start_year => Date.current.year, :end_year => 1920, class:"form-control" %>
    </div>
  </div>
     
  </div>

  <div class="field">
    <div class="form-group col-6">
    <div class="field"></div>
      <%= form.text_field :celular2, placeholder:"Celular 2", class:"form-control" %>
     </div> 
  </div>

<%# <%   <div class="field">
<%#    <%= form.label :"telefone 2" %>
<%#    <%= form.text_field :telefone2 %>
<%#  </div> %>

<%# <div class="field">
    <%= form.label :"nome de contato 2" %>
<%#    <%= form.text_field :nomecont2 %>
 <%# </div> %>

  <div class="field">
    <div class="field"></div>
    <div class="form-group col-6">
      <%= form.text_field :email, placeholder: "email", class: "form-control" %>
     </div>
  </div>

  <div class="field">
    <div class="field"></div>
    <div class="form-group col-2">    
      <%= form.text_field :cep, placeholder: "CEP", class: "form-control" %>
    </div>
  </div>

  <div class="field">
    <div class="field"></div>
    <div class="form-group col-6">   
     <%= form.text_area :rua, placeholder: "Rua", class: "form-control" %>
    </div> 
  </div>

  <div class="field">
    <div class="field"></div>
    <div class="form-group col-1"> 
      <%= form.text_field :numcasa, placeholder: "Nº", class: "form-control" %>
    </div>
  </div>

  <div class="field">
    <div class="field"></div>
      <div class="form-group col-6"> 
      <%= form.text_field :cidade, placeholder: "Cidade", class: "form-control" %>
    </div>
  </div>

  <div class="field">
    <div class="field"></div>
      <div class="form-group col-6"> 
      <%= form.text_area :bairro, placeholder: "Bairro", class: "form-control" %>
     </div> 
  </div>

  <div class="field">
    <div class="field"></div>
    <div class="form-group col-6"> 
      <%= form.text_field :estado, placeholder: "Estado", class: "form-control" %>
    </div>
  </div>

  <div class="field">
    <div class="field"></div>
    <div class="form-group col-6">   
      <%= form.text_field :pais, placeholder: "País", class: "form-control" %>
    </div>  
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cads/edit.html.erb
<h1>Editar cadastro</h1>

<%= render 'form', cad: @cad %>

<%= link_to 'Show', @cad %> |
<%= link_to 'Back', cads_path %>

app/views/cads/index.html.erb
  <p id="notice"><%= notice %></p>

  <h1>Cadastro</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="row">Celular</th>
        <th scope="row">Telefone</th>
        <th scope="row">CNPJ/CPF</th>
        <th scope="row">Email</th>
        <th scope="row">Rua</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @cads.each do |cad| %>
        <tr>
          <td><%= cad.nome %></td>
          <td><%= cad.celular %></td>
          <td><%= cad.telefone %></td>
          <td><%= cad.cnpjcpf %></td>
          <td><%= cad.email %></td>
          <td><%= cad.rua %></td>
          <td><%= link_to 'Mostrar', cad %></td><form>
          <td><%= link_to 'Editar', edit_cad_path(cad) %></td>
          <td><%= link_to 'Excluir', cad, method: :delete, data: { confirm: 'Voce tem certeza que deseja excluir?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Novo Cadastro', new_cad_path %>

app/views/cads/new.html.erb
<h1>Novo Cadastro</h1>

<%= render 'form', cad: @cad %>

<%= link_to 'Back', cads_path %>

app/views/cads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cad.nome %>
</p>

<p>
  <strong>Cnpjcpf:</strong>
  <%= @cad.cnpjcpf %>
</p>

<p>
  <strong>Ie:</strong>
  <%= @cad.ie %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @cad.celular %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cad.telefone %>
</p>

<p>
  <strong>Nomecont:</strong>
  <%= @cad.nomecont %>
</p>

<p>
  <strong>Dtnasc:</strong>
  <%= @cad.dtnasc %>
</p>

<p>
  <strong>Celular2:</strong>
  <%= @cad.celular2 %>
</p>

<p>
  <strong>Telefone2:</strong>
  <%= @cad.telefone2 %>
</p>

<p>
  <strong>Nomecont2:</strong>
  <%= @cad.nomecont2 %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cad.email %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @cad.cep %>
</p>

<p>
  <strong>Rua:</strong>
  <%= @cad.rua %>
</p>

<p>
  <strong>Numcasa:</strong>
  <%= @cad.numcasa %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @cad.cidade %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @cad.bairro %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @cad.estado %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @cad.pais %>
</p>

<%= link_to 'Edit', edit_cad_path(@cad) %> |
<%= link_to 'Back', cads_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Central Pet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>